"""Added Location model and updated Affaire and User models with necessary changes.

Revision ID: 4e0a17498c11
Revises: dcd285fb9c0e
Create Date: 2024-04-22 11:24:49.961282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0a17498c11'
down_revision = 'dcd285fb9c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('affaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('affaires')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('affaires',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"affaires_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('DEP_CODE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('COM_CODE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Precision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['COM_CODE'], ['communes.COM_CODE'], name='affaires_COM_CODE_fkey'),
    sa.ForeignKeyConstraint(['DEP_CODE'], ['departements.DEP_CODE'], name='affaires_DEP_CODE_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='affaires_user_id_fkey'),
    sa.PrimaryKeyConstraint('ID', name='affaires_pkey'),
    sa.UniqueConstraint('Nom', name='affaires_Nom_key')
    )
    op.drop_table('affaire')
    op.drop_table('user')
    # ### end Alembic commands ###
