"""empty message

Revision ID: 621f364c81fd
Revises: 
Create Date: 2024-02-29 14:54:39.184913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621f364c81fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communes')
    op.drop_table('affaires')
    op.drop_table('departements')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('departements',
    sa.Column('DEP_CODE', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('DEP_NOM', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('DEP_CODE', name='departements_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('affaires',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"affaires_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('DEP_CODE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('COM_CODE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Precision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['COM_CODE'], ['communes.COM_CODE'], name='affaires_COM_CODE_fkey'),
    sa.ForeignKeyConstraint(['DEP_CODE'], ['departements.DEP_CODE'], name='affaires_DEP_CODE_fkey'),
    sa.PrimaryKeyConstraint('ID', name='affaires_pkey')
    )
    op.create_table('communes',
    sa.Column('COM_CODE', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('COM_NOM', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('DEP_CODE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DEP_CODE'], ['departements.DEP_CODE'], name='communes_DEP_CODE_fkey'),
    sa.PrimaryKeyConstraint('COM_CODE', name='communes_pkey')
    )
    # ### end Alembic commands ###
